import { env } from '@/lib/runtime';
import { readOperations } from '@/lib/operations';
import { getTfAccess, getTfOwner, hasTfPermission } from '../../chatgpt-auth';

const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'cache-control':'no-store, no-cache, must-revalidate','pragma':'no-cache'}});
const normalizedGgAdjustment=(item:any)=>({operationId:item.operation_id,ilaRate:Number(item.ila_rate_bps||0)===2600?26.6:Number(item.ila_rate_bps||0)/100,invoiceRate:Number(item.invoice_rate_bps||0)/100,tfShare:Number(item.tf_share_bps??5000)/100});

export async function GET(){
  const user=await getTfAccess();
  if(!user||!hasTfPermission(user,'parceiros'))return json({error:'Não autorizado'},401);
  const rows=user.partnerId
    ?await env.DB.prepare("SELECT id,name,tax_rate_bps,invoice_rate_bps,tf_share_bps FROM partners WHERE id=? AND owner_id IN (?,?) AND active=1 AND deleted_at IS NULL").bind(user.partnerId,user.ownerKeys[0],user.ownerKeys[1]).all<{id:number;name:string;tax_rate_bps:number;invoice_rate_bps:number;tf_share_bps:number}>()
    :await env.DB.prepare("SELECT id,name,tax_rate_bps,invoice_rate_bps,tf_share_bps FROM partners WHERE owner_id IN (?,?) AND active=1 AND deleted_at IS NULL ORDER BY lower(name)").bind(user.ownerKeys[0],user.ownerKeys[1]).all<{id:number;name:string;tax_rate_bps:number;invoice_rate_bps:number;tf_share_bps:number}>();
  const settlements=user.partnerId
    ?await env.DB.prepare("SELECT partner_id,period,gross_commission_cents,fee_rate_bps,tf_share_bps,status,paid_at,bonus_cents,bonus_description FROM partner_settlements WHERE partner_id=? AND owner_id IN (?,?) ORDER BY period DESC").bind(user.partnerId,user.ownerKeys[0],user.ownerKeys[1]).all<any>()
    :await env.DB.prepare("SELECT partner_id,period,gross_commission_cents,fee_rate_bps,tf_share_bps,status,paid_at,bonus_cents,bonus_description FROM partner_settlements WHERE owner_id IN (?,?) ORDER BY period DESC").bind(user.ownerKeys[0],user.ownerKeys[1]).all<any>();
  const adjustmentSql="SELECT a.partner_id,a.operation_id,a.ila_rate_bps,a.invoice_rate_bps,a.tf_share_bps FROM partner_operation_adjustments a JOIN operations o ON o.id=a.operation_id AND o.deleted_at IS NULL";
  const adjustments=user.partnerId
    ?await env.DB.prepare(`${adjustmentSql} WHERE a.partner_id=? AND a.owner_id IN (?,?)`).bind(user.partnerId,user.ownerKeys[0],user.ownerKeys[1]).all<any>()
    :await env.DB.prepare(`${adjustmentSql} WHERE a.owner_id IN (?,?)`).bind(user.ownerKeys[0],user.ownerKeys[1]).all<any>();
  const bonuses=user.partnerId
    ?await env.DB.prepare("SELECT o.partner_id,substr(cm.expected_at,1,7) AS period,SUM(cm.value_cents) AS value_cents,MAX(cm.notes) AS description FROM commissions cm JOIN operations o ON o.id=cm.operation_id WHERE cm.deleted_at IS NULL AND cm.rate_bps IS NULL AND lower(COALESCE(cm.notes,'')) LIKE 'bonificação parceiro gg%' AND o.partner_id=? GROUP BY o.partner_id,substr(cm.expected_at,1,7)").bind(user.partnerId).all<any>()
    :await env.DB.prepare("SELECT o.partner_id,substr(cm.expected_at,1,7) AS period,SUM(cm.value_cents) AS value_cents,MAX(cm.notes) AS description FROM commissions cm JOIN operations o ON o.id=cm.operation_id WHERE cm.deleted_at IS NULL AND cm.rate_bps IS NULL AND lower(COALESCE(cm.notes,'')) LIKE 'bonificação parceiro gg%' GROUP BY o.partner_id,substr(cm.expected_at,1,7)").all<any>();
  const operations=await readOperations(env.DB,user);
  return json({partners:rows.results.map(row=>{const partnerSettlements=settlements.results.filter((item:any)=>item.partner_id===row.id),legacyBonuses=bonuses.results.filter((item:any)=>item.partner_id===row.id).map((item:any)=>({period:item.period,value:(item.value_cents||0)/100,description:item.description||'Bonificação',source:'legacy'})),manualBonuses=partnerSettlements.filter((item:any)=>Number(item.bonus_cents||0)>0).map((item:any)=>({period:item.period,value:Number(item.bonus_cents||0)/100,description:item.bonus_description||'Bônus / campanha adicional',source:'manual'}));return {id:row.id,name:row.name,taxRate:(row.tax_rate_bps||0)/100,invoiceRate:(row.invoice_rate_bps||0)/100,tfShare:(row.tf_share_bps||5000)/100,settlements:partnerSettlements.map((item:any)=>({period:item.period,grossCommission:operations.filter(operation=>(operation.partnerId===row.id||operation.origin.localeCompare(row.name,'pt-BR',{sensitivity:'base'})===0)&&operation.date.startsWith(item.period)).reduce((sum,operation)=>sum+operation.grossCommission,0),feeRate:(item.fee_rate_bps||201)/100,tfShare:(item.tf_share_bps||5000)/100,status:item.status||'em_aberto',paidAt:item.paid_at||'',bonus:Number(item.bonus_cents||0)/100,bonusDescription:item.bonus_description||''})),adjustments:adjustments.results.filter((item:any)=>item.partner_id===row.id).map(normalizedGgAdjustment),bonuses:[...legacyBonuses,...manualBonuses]};})});
}

export async function POST(request:Request){
  const user=await getTfOwner();
  if(!user)return json({error:'Não autorizado'},401);
  const body=await request.json() as {name?:string},name=String(body.name||'').trim();
  if(name.length<2)return json({error:'Informe o nome do parceiro.'},400);
  const existing=await env.DB.prepare("SELECT id,name,tax_rate_bps,invoice_rate_bps,tf_share_bps FROM partners WHERE owner_id IN (?,?) AND lower(name)=lower(?) AND deleted_at IS NULL LIMIT 1").bind(user.ownerKey,user.email,name).first<{id:number;name:string;tax_rate_bps:number;invoice_rate_bps:number;tf_share_bps:number}>();
  if(existing)return json({partner:{id:existing.id,name:existing.name,taxRate:(existing.tax_rate_bps||0)/100,invoiceRate:(existing.invoice_rate_bps||0)/100,tfShare:(existing.tf_share_bps||5000)/100}});
  const now=Date.now(),partner=await env.DB.prepare("INSERT INTO partners (owner_id,name,active,created_at,updated_at) VALUES (?,?,1,?,?) RETURNING id,name").bind(user.ownerKey,name,now,now).first<{id:number;name:string}>();
  return partner?json({partner:{...partner,taxRate:0,invoiceRate:0,tfShare:50}},201):json({error:'Não foi possível cadastrar o parceiro.'},500);
}

export async function PATCH(request:Request){
  const user=await getTfOwner();if(!user)return json({error:'Não autorizado'},401);
  const body=await request.json() as {id?:number;operationId?:number;ilaRate?:number;taxRate?:number;invoiceRate?:number;tfShare?:number;period?:string;status?:string;grossCommission?:number;bonus?:number;bonusDescription?:string},id=Number(body.id);if(!id)return json({error:'Parceiro inválido.'},400);
  const clamp=(value:unknown)=>Math.max(0,Math.min(100,Number(value||0)));
  if(Number(body.operationId)>0){const operationId=Number(body.operationId),owned=await env.DB.prepare("SELECT id FROM operations WHERE id=? AND owner_id IN (?,?) AND deleted_at IS NULL AND (partner_id=? OR lower(origin)=(SELECT lower(name) FROM partners WHERE id=?))").bind(operationId,user.ownerKey,user.email,id,id).first();if(!owned)return json({error:'Operação do parceiro não encontrada.'},404);const ilaRate=clamp(body.ilaRate),invoiceRate=clamp(body.invoiceRate),tfShare=clamp(body.tfShare||50),now=Date.now();await env.DB.prepare("INSERT INTO partner_operation_adjustments (owner_id,partner_id,operation_id,ila_rate_bps,invoice_rate_bps,tf_share_bps,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(operation_id) DO UPDATE SET partner_id=excluded.partner_id,ila_rate_bps=excluded.ila_rate_bps,invoice_rate_bps=excluded.invoice_rate_bps,tf_share_bps=excluded.tf_share_bps,updated_at=excluded.updated_at").bind(user.ownerKey,id,operationId,Math.round(ilaRate*100),Math.round(invoiceRate*100),Math.round(tfShare*100),now,now).run();return json({adjustment:{operationId,ilaRate,invoiceRate,tfShare}});}
  if(/^\d{4}-\d{2}$/.test(String(body.period||''))&&body.bonus!==undefined){const owned=await env.DB.prepare("SELECT id FROM partners WHERE id=? AND owner_id IN (?,?) AND deleted_at IS NULL").bind(id,user.ownerKey,user.email).first();if(!owned)return json({error:'Parceiro não encontrado.'},404);const period=String(body.period),rawBonus=Number(body.bonus);if(!Number.isFinite(rawBonus)||rawBonus<0)return json({error:'O valor adicional deve ser um número igual ou maior que zero.'},400);const bonusCents=Math.round(rawBonus*100),description=String(body.bonusDescription||'').trim().slice(0,160)||null,now=Date.now(),rawGross=Number(body.grossCommission||0);if(!Number.isFinite(rawGross)||rawGross<0)return json({error:'A comissão bruta informada é inválida.'},400);const gross=Math.round(rawGross*100),settlement=await env.DB.prepare("INSERT INTO partner_settlements (owner_id,partner_id,period,gross_commission_cents,fee_rate_bps,tf_share_bps,status,paid_at,bonus_cents,bonus_description,created_at,updated_at) VALUES (?,?,?,?,201,5000,'em_aberto',NULL,?,?,?,?) ON CONFLICT(partner_id,period) DO UPDATE SET bonus_cents=excluded.bonus_cents,bonus_description=excluded.bonus_description,updated_at=excluded.updated_at RETURNING period,gross_commission_cents,fee_rate_bps,tf_share_bps,status,paid_at,bonus_cents,bonus_description").bind(user.ownerKey,id,period,gross,bonusCents,description,now,now).first<any>();return json({settlement:{period:settlement?.period||period,grossCommission:Number(settlement?.gross_commission_cents||0)/100,feeRate:Number(settlement?.fee_rate_bps||201)/100,tfShare:Number(settlement?.tf_share_bps||5000)/100,status:settlement?.status||'em_aberto',paidAt:settlement?.paid_at||'',bonus:Number(settlement?.bonus_cents||0)/100,bonusDescription:settlement?.bonus_description||''}});}
  if(/^\d{4}-\d{2}$/.test(String(body.period||''))){const owned=await env.DB.prepare("SELECT id FROM partners WHERE id=? AND owner_id IN (?,?) AND deleted_at IS NULL").bind(id,user.ownerKey,user.email).first();if(!owned)return json({error:'Parceiro não encontrado.'},404);const period=String(body.period),status=body.status==='pago'?'pago':'em_aberto',paidAt=status==='pago'?new Date().toISOString().slice(0,10):null,now=Date.now(),gross=Math.round((await readOperations(env.DB,{ownerKeys:[user.ownerKey,user.email],role:'admin',memberId:null,partnerId:null})).filter(operation=>operation.partnerId===id&&operation.date.startsWith(period)).reduce((sum,operation)=>sum+operation.grossCommission,0)*100);await env.DB.prepare("INSERT INTO partner_settlements (owner_id,partner_id,period,gross_commission_cents,fee_rate_bps,tf_share_bps,status,paid_at,created_at,updated_at) VALUES (?,?,?,?,201,5000,?,?,?,?) ON CONFLICT(partner_id,period) DO UPDATE SET gross_commission_cents=excluded.gross_commission_cents,status=excluded.status,paid_at=excluded.paid_at,updated_at=excluded.updated_at").bind(user.ownerKey,id,period,gross,status,paidAt,now,now).run();return json({settlement:{period,status,paidAt,grossCommission:gross/100,feeRate:2.01,tfShare:50}});}
  const taxRate=clamp(body.taxRate),invoiceRate=clamp(body.invoiceRate),tfShare=clamp(body.tfShare),now=Date.now();
  const partner=await env.DB.prepare("UPDATE partners SET tax_rate_bps=?,invoice_rate_bps=?,tf_share_bps=?,updated_at=? WHERE id=? AND owner_id IN (?,?) AND deleted_at IS NULL RETURNING id,name").bind(Math.round(taxRate*100),Math.round(invoiceRate*100),Math.round(tfShare*100),now,id,user.ownerKey,user.email).first<{id:number;name:string}>();
  return partner?json({partner:{...partner,taxRate,invoiceRate,tfShare}}):json({error:'Parceiro não encontrado.'},404);
}
