ALTER TABLE partners ADD COLUMN tax_rate_bps INTEGER NOT NULL DEFAULT 0;
ALTER TABLE partners ADD COLUMN invoice_rate_bps INTEGER NOT NULL DEFAULT 0;
ALTER TABLE partners ADD COLUMN tf_share_bps INTEGER NOT NULL DEFAULT 5000;
