-- PostgreSQL schema, translated from all 13 original SQLite migrations.

-- Amounts and timestamps remain exact integers; dates retain their original text format.

CREATE TABLE "access_users" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "email" text NOT NULL,
  "name" text NOT NULL,
  "permissions_json" text NOT NULL DEFAULT '["inicio","atendimento"]',
  "active" bigint NOT NULL DEFAULT 1,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL,
  "partner_id" bigint
);

CREATE INDEX "idx_access_users_email_active" ON "access_users" ("email","active");

CREATE UNIQUE INDEX "access_users_owner_email_unique" ON "access_users" ("owner_id","email");

CREATE TABLE "activities" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "deal_id" bigint,
  "type" text NOT NULL,
  "title" text NOT NULL,
  "due_at" bigint,
  "completed_at" bigint
);

CREATE INDEX "idx_activities_owner_due" ON "activities" ("owner_id","due_at");

CREATE TABLE "audit_log" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "user_id" text,
  "entity_type" text NOT NULL,
  "entity_id" text NOT NULL,
  "action" text NOT NULL,
  "before_json" text,
  "after_json" text,
  "created_at" bigint NOT NULL
);

CREATE INDEX "idx_audit_owner_entity" ON "audit_log" ("owner_id","entity_type","entity_id");

CREATE TABLE "automations" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "name" text NOT NULL,
  "trigger_type" text NOT NULL,
  "action_type" text NOT NULL,
  "active" bigint NOT NULL DEFAULT 1
);

CREATE TABLE "client_documents" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "client_id" bigint NOT NULL,
  "file_key" text NOT NULL,
  "file_name" text NOT NULL,
  "mime_type" text NOT NULL,
  "size_bytes" bigint NOT NULL,
  "document_type" text NOT NULL DEFAULT 'outro',
  "created_at" bigint NOT NULL
);

CREATE INDEX "idx_client_documents_owner_client" ON "client_documents" ("owner_id","client_id");

CREATE TABLE "clients" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "name" text NOT NULL,
  "normalized_name" text NOT NULL,
  "cpf" text,
  "benefit_number" text,
  "birth_date" text,
  "phone" text,
  "email" text,
  "address" text,
  "city" text,
  "notes" text,
  "source_row" text,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL,
  "deleted_at" bigint
);

CREATE INDEX "idx_clients_owner_phone" ON "clients" ("owner_id","phone");

CREATE INDEX "idx_clients_owner_benefit" ON "clients" ("owner_id","benefit_number");

CREATE INDEX "idx_clients_owner_name" ON "clients" ("owner_id","normalized_name");

CREATE UNIQUE INDEX "clients_owner_cpf_unique" ON "clients" ("owner_id","cpf");

CREATE TABLE "commissions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "operation_id" bigint NOT NULL,
  "rate_bps" bigint,
  "value_cents" bigint NOT NULL DEFAULT 0,
  "expected_at" text,
  "received_at" text,
  "status" text NOT NULL DEFAULT 'prevista',
  "notes" text,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL,
  "deleted_at" bigint
);

CREATE TABLE "companies" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "name" text NOT NULL,
  "segment" text,
  "created_at" bigint NOT NULL
);

CREATE INDEX "idx_companies_owner_id" ON "companies" ("owner_id");

CREATE TABLE "contacts" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" bigint,
  "name" text NOT NULL,
  "email" text,
  "phone" text
);

CREATE TABLE "deal_documents" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "deal_id" bigint NOT NULL,
  "file_key" text NOT NULL,
  "file_name" text NOT NULL,
  "mime_type" text NOT NULL,
  "size_bytes" bigint NOT NULL,
  "document_type" text NOT NULL DEFAULT 'identidade',
  "created_at" bigint NOT NULL
);

CREATE INDEX "idx_deal_documents_owner_deal" ON "deal_documents" ("owner_id","deal_id");

CREATE TABLE "deal_history" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "deal_id" bigint NOT NULL,
  "operation_id" bigint,
  "event_type" text NOT NULL,
  "description" text NOT NULL,
  "before_json" text,
  "after_json" text,
  "source" text NOT NULL DEFAULT 'Gestão TF',
  "created_at" bigint NOT NULL
);

CREATE INDEX "idx_deal_history_owner_deal" ON "deal_history" ("owner_id","deal_id","created_at");

CREATE TABLE "deals" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "company_id" bigint,
  "title" text NOT NULL,
  "value_cents" bigint NOT NULL DEFAULT 0,
  "stage" text NOT NULL,
  "status" text NOT NULL DEFAULT 'open',
  "expected_close_at" bigint,
  "updated_at" bigint NOT NULL,
  "lead_score" bigint NOT NULL DEFAULT 0,
  "source" text,
  "probability" bigint NOT NULL DEFAULT 0,
  "recurring_value_cents" bigint NOT NULL DEFAULT 0,
  "client_id" bigint,
  "operation_id" bigint,
  "payload_json" text,
  "created_at" bigint NOT NULL DEFAULT 0,
  "needs_completion" bigint NOT NULL DEFAULT 0,
  "assigned_user_id" bigint
);

CREATE INDEX "idx_deals_owner_assignee_stage" ON "deals" ("owner_id","assigned_user_id","stage");

CREATE INDEX "idx_deals_owner_operation" ON "deals" ("owner_id","operation_id");

CREATE INDEX "idx_deals_owner_client" ON "deals" ("owner_id","client_id");

CREATE INDEX "idx_deals_owner_stage" ON "deals" ("owner_id","stage");

CREATE TABLE "gestor_tf_audit" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "actor_role" text NOT NULL,
  "whatsapp_phone" text NOT NULL,
  "message_id" text,
  "command_text" text NOT NULL,
  "action" text NOT NULL,
  "client_id" bigint,
  "operation_id" bigint,
  "deal_id" bigint,
  "before_json" text,
  "after_json" text,
  "created_at" bigint NOT NULL
);

CREATE INDEX "idx_gestor_tf_audit_owner_created" ON "gestor_tf_audit" ("owner_id","created_at");

CREATE TABLE "import_batches" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "file_name" text NOT NULL,
  "backup_key" text,
  "row_count" bigint NOT NULL DEFAULT 0,
  "unique_clients" bigint NOT NULL DEFAULT 0,
  "merged_clients" bigint NOT NULL DEFAULT 0,
  "preserved_operations" bigint NOT NULL DEFAULT 0,
  "possible_duplicates" bigint NOT NULL DEFAULT 0,
  "missing_cpf" bigint NOT NULL DEFAULT 0,
  "inconsistencies" bigint NOT NULL DEFAULT 0,
  "status" text NOT NULL DEFAULT 'analisando',
  "created_at" bigint NOT NULL
);

CREATE TABLE "institutions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "name" text NOT NULL,
  "category" text,
  "url" text,
  "logo_key" text,
  "notes" text,
  "active" bigint NOT NULL DEFAULT 1,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL,
  "deleted_at" bigint
);

CREATE TABLE "invoices" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "number" text NOT NULL,
  "client_id" bigint,
  "partner_id" bigint,
  "service_id" bigint,
  "value_cents" bigint NOT NULL,
  "issued_at" text,
  "paid_at" text,
  "status" text NOT NULL DEFAULT 'pendente',
  "file_key" text,
  "file_name" text,
  "notes" text,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL,
  "deleted_at" bigint
);

CREATE TABLE "operations" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "client_id" bigint NOT NULL,
  "partner_id" bigint,
  "service_id" bigint,
  "bank" text,
  "promoter" text,
  "original_product" text,
  "category" text,
  "producer" text,
  "origin" text,
  "location" text,
  "benefit_number" text,
  "contract_number" text,
  "value_cents" bigint DEFAULT 0,
  "installment_cents" bigint DEFAULT 0,
  "term" bigint,
  "operation_date" text,
  "paid_at" text,
  "completed_at" text,
  "status" text NOT NULL DEFAULT 'novo_cliente',
  "notes" text,
  "source_row" text,
  "dedupe_fingerprint" text,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL,
  "deleted_at" bigint,
  "vehicle_plate" text,
  "vehicle_name" text,
  "vehicle_model" text,
  "vehicle_year" bigint,
  "vehicle_value_cents" bigint DEFAULT 0,
  "financed_value_cents" bigint DEFAULT 0,
  "down_payment_cents" bigint DEFAULT 0,
  "desired_credit_cents" bigint DEFAULT 0,
  "assigned_user_id" bigint
);

CREATE INDEX "idx_operations_owner_assignee" ON "operations" ("owner_id","assigned_user_id");

CREATE INDEX "idx_operations_dedupe" ON "operations" ("owner_id","dedupe_fingerprint");

CREATE INDEX "idx_operations_owner_client_date" ON "operations" ("owner_id","client_id","operation_date");

CREATE TABLE "partner_operation_adjustments" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "partner_id" bigint NOT NULL,
  "operation_id" bigint NOT NULL,
  "ila_rate_bps" bigint NOT NULL DEFAULT 0,
  "invoice_rate_bps" bigint NOT NULL DEFAULT 201,
  "tf_share_bps" bigint NOT NULL DEFAULT 5000,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL
);

CREATE INDEX "idx_partner_operation_adjustments_owner_partner" ON "partner_operation_adjustments" ("owner_id","partner_id");

CREATE UNIQUE INDEX "partner_operation_adjustments_operation_unique" ON "partner_operation_adjustments" ("operation_id");

CREATE TABLE "partner_settlements" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "partner_id" bigint NOT NULL,
  "period" text NOT NULL,
  "gross_commission_cents" bigint NOT NULL DEFAULT 0,
  "fee_rate_bps" bigint NOT NULL DEFAULT 201,
  "tf_share_bps" bigint NOT NULL DEFAULT 5000,
  "status" text NOT NULL DEFAULT 'em_aberto',
  "paid_at" text,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL
);

CREATE INDEX "idx_partner_settlements_owner_period" ON "partner_settlements" ("owner_id","period");

CREATE UNIQUE INDEX "partner_settlements_partner_period_unique" ON "partner_settlements" ("partner_id","period");

CREATE TABLE "partners" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "name" text NOT NULL,
  "trade_name" text,
  "document" text,
  "phone" text,
  "whatsapp" text,
  "email" text,
  "address" text,
  "contact_name" text,
  "partnership_type" text,
  "started_at" text,
  "notes" text,
  "active" bigint NOT NULL DEFAULT 1,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL,
  "deleted_at" bigint,
  "tax_rate_bps" bigint NOT NULL DEFAULT 0,
  "invoice_rate_bps" bigint NOT NULL DEFAULT 0,
  "tf_share_bps" bigint NOT NULL DEFAULT 5000
);

CREATE TABLE "products" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "name" text NOT NULL,
  "price_cents" bigint NOT NULL,
  "active" bigint NOT NULL DEFAULT 1
);

CREATE TABLE "proposals" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "deal_id" bigint,
  "status" text NOT NULL DEFAULT 'draft',
  "total_cents" bigint NOT NULL,
  "viewed_at" bigint,
  "accepted_at" bigint
);

CREATE TABLE "services" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "name" text NOT NULL,
  "category" text,
  "description" text,
  "price_cents" bigint DEFAULT 0,
  "advisory_fee_cents" bigint DEFAULT 0,
  "commission_rate_bps" bigint DEFAULT 0,
  "institution" text,
  "notes" text,
  "active" bigint NOT NULL DEFAULT 1,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL,
  "deleted_at" bigint
);

CREATE TABLE "users" (
  "id" text PRIMARY KEY,
  "email" text NOT NULL,
  "name" text,
  "role" text NOT NULL DEFAULT 'admin',
  "active" bigint NOT NULL DEFAULT 1,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL,
  "deleted_at" bigint
);

CREATE UNIQUE INDEX "users_email_unique" ON "users" ("email");

CREATE TABLE "whatsapp_integrations" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "admin_phone" text NOT NULL,
  "phone_number_id" text NOT NULL,
  "display_phone" text,
  "enabled" bigint NOT NULL DEFAULT 1,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL
);

CREATE UNIQUE INDEX "whatsapp_integrations_phone_number_id_unique" ON "whatsapp_integrations" ("phone_number_id");

CREATE UNIQUE INDEX "whatsapp_integrations_owner_unique" ON "whatsapp_integrations" ("owner_id");

CREATE TABLE "whatsapp_messages" (
  "message_id" text PRIMARY KEY,
  "owner_id" text,
  "from_phone" text NOT NULL,
  "message_type" text NOT NULL,
  "command_text" text,
  "status" text NOT NULL,
  "error_text" text,
  "received_at" bigint NOT NULL,
  "processed_at" bigint
);

CREATE INDEX "idx_whatsapp_messages_owner_received" ON "whatsapp_messages" ("owner_id","received_at");

CREATE TABLE "whatsapp_pending_actions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" text NOT NULL,
  "from_phone" text NOT NULL,
  "kind" text NOT NULL,
  "payload_json" text NOT NULL,
  "status" text NOT NULL DEFAULT 'pendente',
  "created_at" bigint NOT NULL,
  "expires_at" bigint NOT NULL
);

CREATE INDEX "idx_whatsapp_pending_owner_phone" ON "whatsapp_pending_actions" ("owner_id","from_phone","status","expires_at");

ALTER TABLE "access_users" ADD FOREIGN KEY ("partner_id") REFERENCES "partners" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "activities" ADD FOREIGN KEY ("deal_id") REFERENCES "deals" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "client_documents" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "commissions" ADD FOREIGN KEY ("operation_id") REFERENCES "operations" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "contacts" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "deal_documents" ADD FOREIGN KEY ("deal_id") REFERENCES "deals" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "deal_history" ADD FOREIGN KEY ("operation_id") REFERENCES "operations" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "deal_history" ADD FOREIGN KEY ("deal_id") REFERENCES "deals" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "deals" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "deals" ADD FOREIGN KEY ("assigned_user_id") REFERENCES "access_users" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "deals" ADD FOREIGN KEY ("operation_id") REFERENCES "operations" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "deals" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "gestor_tf_audit" ADD FOREIGN KEY ("deal_id") REFERENCES "deals" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "gestor_tf_audit" ADD FOREIGN KEY ("operation_id") REFERENCES "operations" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "gestor_tf_audit" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "operations" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "operations" ADD FOREIGN KEY ("partner_id") REFERENCES "partners" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "operations" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "operations" ADD FOREIGN KEY ("assigned_user_id") REFERENCES "access_users" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "partner_operation_adjustments" ADD FOREIGN KEY ("operation_id") REFERENCES "operations" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "partner_operation_adjustments" ADD FOREIGN KEY ("partner_id") REFERENCES "partners" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "partner_settlements" ADD FOREIGN KEY ("partner_id") REFERENCES "partners" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "proposals" ADD FOREIGN KEY ("deal_id") REFERENCES "deals" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE operations ADD COLUMN is_historical bigint NOT NULL DEFAULT 0;

ALTER TABLE operations ADD COLUMN report_excluded bigint NOT NULL DEFAULT 0;

CREATE INDEX idx_operations_reporting ON operations (report_excluded,deleted_at,operation_date);

CREATE TABLE stored_files (key text PRIMARY KEY,body bytea NOT NULL,content_type text NOT NULL,updated_at bigint NOT NULL);

CREATE TABLE source_records (source text NOT NULL,source_id text NOT NULL,entity_type text,entity_id bigint,payload jsonb NOT NULL,PRIMARY KEY(source,source_id));

CREATE TABLE migration_runs (name text PRIMARY KEY,source_hash text NOT NULL,summary jsonb NOT NULL,completed_at bigint NOT NULL);

CREATE TABLE app_settings (key text PRIMARY KEY,value text NOT NULL);

CREATE TABLE auth_credentials (user_id text PRIMARY KEY REFERENCES users(id),password_hash text NOT NULL,updated_at bigint NOT NULL);

CREATE TABLE auth_sessions (token_hash text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),created_at bigint NOT NULL,expires_at bigint NOT NULL);

CREATE INDEX idx_auth_sessions_expiry ON auth_sessions(expires_at);

CREATE TABLE auth_attempts (key text PRIMARY KEY,attempts bigint NOT NULL,window_start bigint NOT NULL);

ALTER TABLE users ADD COLUMN cpf text;

CREATE UNIQUE INDEX users_cpf_unique ON users(cpf);
