CREATE TABLE IF NOT EXISTS post_sale_tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id text NOT NULL,
  operation_id bigint NOT NULL,
  client_id bigint NOT NULL,
  status text NOT NULL DEFAULT 'pendente',
  completed_at bigint,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS post_sale_tasks_operation_unique ON post_sale_tasks (operation_id);
CREATE INDEX IF NOT EXISTS idx_post_sale_tasks_owner_status ON post_sale_tasks (owner_id,status,updated_at);
ALTER TABLE post_sale_tasks ADD FOREIGN KEY (operation_id) REFERENCES operations (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE post_sale_tasks ADD FOREIGN KEY (client_id) REFERENCES clients (id) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS crm_catalog_options (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id text NOT NULL,
  kind text NOT NULL,
  label text NOT NULL,
  normalized_label text NOT NULL,
  active bigint NOT NULL DEFAULT 1,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS crm_catalog_options_owner_kind_label_unique ON crm_catalog_options (owner_id,kind,normalized_label);
CREATE INDEX IF NOT EXISTS idx_crm_catalog_options_owner_kind ON crm_catalog_options (owner_id,kind,active);
UPDATE crm_catalog_options SET active=0,updated_at=EXTRACT(EPOCH FROM NOW())::bigint*1000 WHERE normalized_label='teste 3';
