'use client';

import { useState } from 'react';

type Result = { ok?: boolean; error?: string; parsed?: { operations: number; bonus: boolean }; test?: { counts?: Record<string, number> }; result?: Record<string, unknown> };

export default function ImportGgClient() {
  const [text,setText]=useState(''),[fileName,setFileName]=useState(''),[testing,setTesting]=useState(false),[importing,setImporting]=useState(false),[validated,setValidated]=useState(false),[result,setResult]=useState<Result|null>(null);
  const choose=async(file?:File)=>{if(!file)return;setFileName(file.name);setText(await file.text());setValidated(false);setResult(null)};
  const send=async(validateOnly:boolean)=>{validateOnly?setTesting(true):setImporting(true);setResult(null);try{const response=await fetch('/api/records',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ggHistoryText:text,ggHistoryValidateOnly:validateOnly,ggHistoryFinanceOnly:!validateOnly,ggAccessPassword:'102030'})}),payload=await response.json() as Result;setResult(payload);if(response.ok&&validateOnly)setValidated(true);if(response.ok&&!validateOnly)setValidated(false)}catch{setResult({error:'Não foi possível concluir a solicitação.'})}finally{setTesting(false);setImporting(false)}};
  return <main className="tf-gg-import-page"><section><a href="/">← Voltar ao painel</a><small>IMPORTAÇÃO ADMINISTRATIVA</small><h1>Base histórica GG Veículos</h1><p>Valide a planilha em um esquema isolado antes de gravar clientes, operações, comissões, pagamentos e o acesso do parceiro.</p><label className="tf-gg-import-file"><input type="file" accept=".txt,.tsv,.csv,text/plain,text/tab-separated-values" onChange={event=>void choose(event.target.files?.[0])}/><b>{fileName||'Selecionar a planilha em texto'}</b><span>{text?`${text.split(/\r?\n/).length} linhas carregadas`:'Nenhum arquivo selecionado'}</span></label><div className="tf-gg-import-actions"><button type="button" disabled={!text||testing||importing} onClick={()=>void send(true)}>{testing?'Validando…':'1. Validar em ambiente isolado'}</button><button className="primary" type="button" disabled={!validated||importing||testing} onClick={()=>void send(false)}>{importing?'Importando…':'2. Importar na base oficial'}</button></div>{result&&<article className={result.error?'error':'success'}>{result.error?<><b>Não foi possível concluir</b><p>{result.error}</p></>:<><b>{result.result?'Importação concluída':'Validação concluída'}</b><p>{result.parsed?.operations||0} operações identificadas · bonificação {result.parsed?.bonus?'identificada':'não identificada'}.</p>{result.test?.counts&&<p>Teste: {Object.entries(result.test.counts).map(([key,value])=>`${key}: ${value}`).join(' · ')}</p>}{result.result&&<pre>{JSON.stringify(result.result,null,2)}</pre>}</>}</article>}</section></main>;
}
